"""Pydantic models for test data structures."""

from datetime import datetime
from pydantic import BaseModel, Field


class Prompt(BaseModel):
    """A test prompt configuration."""
    id: int
    category: str
    text: str
    expected_bash: list[str] = Field(default_factory=list)
    expected_windows: list[str] = Field(default_factory=list)


class PromptsConfig(BaseModel):
    """Configuration file containing all test prompts."""
    prompts: list[Prompt]


class ToolCall(BaseModel):
    """A tool call made by Claude during the test."""
    tool_name: str
    tool_input: dict
    tool_result: str | None = None
    success: bool = True
    error: str | None = None


class TestResult(BaseModel):
    """Result of running a single test prompt."""
    prompt_id: int
    prompt_text: str
    prompt_category: str
    commands_used: list[str] = Field(default_factory=list)
    tool_calls: list[ToolCall] = Field(default_factory=list)
    execution_success: bool = True
    errors: list[str] = Field(default_factory=list)
    output: str = ""
    used_bash_style: bool = False
    used_windows_style: bool = False
    raw_response: str = ""


class TestRun(BaseModel):
    """A complete test run with all results."""
    mcp_enabled: bool
    mcp_server: str | None = None
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
    platform: str = "windows"
    results: list[TestResult] = Field(default_factory=list)
    total_prompts: int = 0
    successful_prompts: int = 0
    failed_prompts: int = 0
    bash_style_count: int = 0
    windows_style_count: int = 0


class ComparisonMetrics(BaseModel):
    """Metrics comparing runs with and without MCP."""
    without_mcp_success_rate: float
    with_mcp_success_rate: float
    improvement_percentage: float
    bash_style_reduction: int
    windows_style_increase: int
    error_reduction: int


class AssessmentReport(BaseModel):
    """Final assessment report generated by Claude."""
    summary: str
    metrics: ComparisonMetrics
    detailed_findings: list[str]
    recommendations: list[str]
    conclusion: str
